In [9]:
import mle_1g

In [ ]:
%time ground_truth_model = mle_1g.main()

Ground Truth Pairwise Similarity
    min: 0.18    mean: 0.50    max: 1.00
(32500, 1)
Observed Ratings
    min: 0.00    mean: 0.48    max: 1.00
    n_obs: 32500 | train_mse: 0.111356 | Correlation (R^2): 0.98
Inferred parameters
    sigmoid lower bound: 0.00    sigmoid upper bound: 1.00    sigmoid midpoint: 0.28    sigmoid rate: 15.64
CPU times: user 4h 15min 54s, sys: 27min 53s, total: 4h 43min 48s
Wall time: 2h 43min 5s


In [15]:
ground_truth_model

AttributeError: 'Rate' object has no attribute 'rho'

In [14]:
print(ground_truth_model)

In [13]:
ground_truth_model.save_weights("weights_ground_truth_model", save_format="tf")

In [31]:
import numpy as np
import itertools
n_stimuli = 10
stimulus_set_self = np.stack(
    (np.arange(n_stimuli), np.arange(n_stimuli)), axis=1
)
stimulus_set_diff = np.asarray(
    list(itertools.combinations(np.arange(n_stimuli), 2))
)
stimulus_set = np.vstack((stimulus_set_self, stimulus_set_diff))

In [32]:
temp = [0,0.25,0.5,0.75,1]
np.random.binomial(1, temp)

array([0, 0, 0, 0, 1])

In [33]:
stimulus_set

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [0, 5],
       [0, 6],
       [0, 7],
       [0, 8],
       [0, 9],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5],
       [1, 6],
       [1, 7],
       [1, 8],
       [1, 9],
       [2, 3],
       [2, 4],
       [2, 5],
       [2, 6],
       [2, 7],
       [2, 8],
       [2, 9],
       [3, 4],
       [3, 5],
       [3, 6],
       [3, 7],
       [3, 8],
       [3, 9],
       [4, 5],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [5, 6],
       [5, 7],
       [5, 8],
       [5, 9],
       [6, 7],
       [6, 8],
       [6, 9],
       [7, 8],
       [7, 9],
       [8, 9]])

In [36]:
stimulus_set = [stimulus_set for i in range(3)]
stimulus_set

[[array([[0, 0],
         [1, 1],
         [2, 2],
         [3, 3],
         [4, 4],
         [5, 5],
         [6, 6],
         [7, 7],
         [8, 8],
         [9, 9],
         [0, 1],
         [0, 2],
         [0, 3],
         [0, 4],
         [0, 5],
         [0, 6],
         [0, 7],
         [0, 8],
         [0, 9],
         [1, 2],
         [1, 3],
         [1, 4],
         [1, 5],
         [1, 6],
         [1, 7],
         [1, 8],
         [1, 9],
         [2, 3],
         [2, 4],
         [2, 5],
         [2, 6],
         [2, 7],
         [2, 8],
         [2, 9],
         [3, 4],
         [3, 5],
         [3, 6],
         [3, 7],
         [3, 8],
         [3, 9],
         [4, 5],
         [4, 6],
         [4, 7],
         [4, 8],
         [4, 9],
         [5, 6],
         [5, 7],
         [5, 8],
         [5, 9],
         [6, 7],
         [6, 8],
         [6, 9],
         [7, 8],
         [7, 9],
         [8, 9]]),
  array([[0, 0],
         [1, 1],
         [2, 2],
         [3,

In [25]:
np.vstack([stimulus_set for i in range(3)])

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9],
       [0, 1],
       [0, 2],
       [0, 3],
       [0, 4],
       [0, 5],
       [0, 6],
       [0, 7],
       [0, 8],
       [0, 9],
       [1, 2],
       [1, 3],
       [1, 4],
       [1, 5],
       [1, 6],
       [1, 7],
       [1, 8],
       [1, 9],
       [2, 3],
       [2, 4],
       [2, 5],
       [2, 6],
       [2, 7],
       [2, 8],
       [2, 9],
       [3, 4],
       [3, 5],
       [3, 6],
       [3, 7],
       [3, 8],
       [3, 9],
       [4, 5],
       [4, 6],
       [4, 7],
       [4, 8],
       [4, 9],
       [5, 6],
       [5, 7],
       [5, 8],
       [5, 9],
       [6, 7],
       [6, 8],
       [6, 9],
       [7, 8],
       [7, 9],
       [8, 9],
       [0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9],
       [0, 1],
       [0,